# PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:15432/quarkus_test
quarkus.datasource.username=quarkus_test
quarkus.datasource.password=quarkus_test

quarkus.hibernate-orm.database.generation=update


# =========================
# OPENAPI
# =========================

quarkus.openapi.generator.spec=warehouse-openapi.yaml
quarkus.openapi.generator.base-package=com.warehouse.api